### ISSUE TITLE
There is a bug in getting the distribution name when there is only one wsl distribution

### ISSUE THREAD

**Issue by HotRockit** [pxlrbt/move-wsl#33] opened 2022-05-15 10:43 UTC
**Script version:**
 - [ ] Bash
 - [x] Powershell
 - [ ] Batch
<img width="504" alt="Snipaste_2022-05-15_18-35-49" src="https://user-images.githubusercontent.com/45550742/168468642-4078664f-e352-4c7c-8215-d98295420d8a.png">

**The type of variable distroList is System.Object， not System.Array when there is only one wsl distribution.**

<img width="662" alt="Snipaste_2022-05-15_18-36-34" src="https://user-images.githubusercontent.com/45550742/168468706-1d4b15f8-5605-42d4-89b1-7c6e81587d7b.png">

**Comment by SayakMukhopadhyay** [comment] 2022-05-16 06:12
> The type of variable distroList is System.Object， not System.Array when there is only one wsl distribution.

~~Why Microsoft, why u do this?~~

~~On a serious note, I think I will create an issue in wsl first and see what they think about this since imo this seems like a bad implementation on wsl's part. If they believe that it is working as intended, then I will push a fix to handle this case.~~

Urgh, this seems like an issue with how `Select-Object` behaves and so is not a wsl issue. I almost made a ticket there and looked like an idiot. Well, I will see if I can fix this.

Thanks for the report.

**Comment by SayakMukhopadhyay** [comment] 2022-05-16 07:17
@HotRockit I have merged a fix. This should hopefully fix your issue. Let me know if the issue persists.

**Closed as completed** 2022-05-16 07:16 UTC
Labels: bug

**Comment by HotRockit** [comment] 2022-05-16 10:34
> @HotRockit I have merged a fix. This should hopefully fix your issue. Let me know if the issue persists.

Thanks, this fix worked for me.
